format: isaac_grasp
format_version: 1.0

object_frame_link: detected_object1
gripper_frame_link: wrist_3_link

grasps:
   grasp_0:
      confidence: 1.0
      position: [-0.25, 0.0, 0.0]
      orientation: {w: 0.7071068, xyz: [0, 0.7071068, 0 ]}
      cspace_position:
         finger_joint: 0.004962080158293247
      pregrasp_cspace_position:
         finger_joint: 6.185195525176823e-05

   grasp_1:
      confidence: 1.0
      position: [-0.25, 0.0, 0.0]
      orientation: {w: 0.7071068, xyz: [0, 0.7071068, 0 ]}
      cspace_position:
         finger_joint: 0.004962080158293247
      pregrasp_cspace_position:
         finger_joint: 6.185195525176823e-05