format: isaac_grasp
format_version: 1.0

object_frame: /target_1
gripper_frame: /Robotiq_2F_85_main/Robotiq_2F_85/base_link

grasps:
   "grasp_0":
      confidence: 1.0
      position: [0.0, 0.0, 0.0]
      orientation: {w:  0.0, xyz: [1.0, 0.0, 0.0]}

   "grasp_1":
      confidence: 1.0
      position: [0.0, 0.0, 0.01]
      orientation: {w:  0.0, xyz: [1.0, 0.0, 0.0]}

